name: Build and Deploy

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Tailwind CSS
      run: npx tailwindcss -i css/style.css -o css/output.css --minify
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-css
        path: css/output.css
        
    # Optional: Deploy to GitHub Pages or other hosting
    # - name: Deploy to GitHub Pages
    #   if: github.ref == 'refs/heads/master'
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./
    #     exclude_assets: '.github,node_modules,.git'